# Generated by Django 3.2.12 on 2022-07-13 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Yibiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(max_length=128, upload_to='img_test_2/', verbose_name='仪表图片')),
                ('img_result', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='识别结果')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.admin', verbose_name='用户')),
            ],
        ),
    ]
