# Generated by Django 3.2.12 on 2022-07-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_imgtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='yibiao',
            name='img_name',
            field=models.CharField(default=3, max_length=128, verbose_name='图片名称'),
            preserve_default=False,
        ),
    ]
