# Generated by Django 3.2.12 on 2022-07-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_yibiao_img_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgtemplate',
            name='a',
            field=models.CharField(default=0, max_length=256, verbose_name='刻度及其对应像素坐标'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imgtemplate',
            name='c_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='圆心x像素坐标'),
        ),
        migrations.AddField(
            model_name='imgtemplate',
            name='c_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='圆心y像素坐标'),
        ),
        migrations.AddField(
            model_name='imgtemplate',
            name='fir_d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='配置0刻度线参数1'),
        ),
        migrations.AddField(
            model_name='imgtemplate',
            name='maxd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最大刻度值'),
        ),
        migrations.AddField(
            model_name='imgtemplate',
            name='scale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='刻度间隔'),
        ),
        migrations.AddField(
            model_name='imgtemplate',
            name='sec_d',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='配置0刻度线参数2'),
        ),
    ]
