# Generated by Django 3.2.12 on 2022-07-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20220715_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.SmallIntegerField(choices=[(1, '用户'), (2, '管理员')], default=1, verbose_name='角色'),
        ),
    ]
