# Generated by Django 3.2.12 on 2022-07-15 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='age',
            field=models.IntegerField(default=1, verbose_name='年龄'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2022, 7, 15, 11, 38, 43, 587814), verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='admin',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='mobile',
            field=models.CharField(default=1, max_length=32, verbose_name='手机号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='name',
            field=models.CharField(default=1, max_length=16, verbose_name='姓名'),
            preserve_default=False,
        ),
    ]
