# Generated by Django 3.2.12 on 2022-07-16 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_admin_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2022, 7, 16, 15, 51, 15, 861137), verbose_name='创建时间'),
        ),
    ]
