# Generated by Django 3.2.12 on 2022-07-19 08:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_alter_admin_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2022, 7, 19, 16, 44, 57, 932460), verbose_name='创建时间'),
        ),
        migrations.CreateModel(
            name='ImgOcrRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(max_length=128, upload_to='rec/', verbose_name='识别图片')),
                ('img_result', models.TextField(verbose_name='识别结果')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.admin', verbose_name='用户')),
            ],
        ),
    ]
