# Generated by Django 3.2.12 on 2022-07-22 02:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_auto_20220719_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2022, 7, 22, 2, 48, 44, 1072, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
