# Generated by Django 3.2.12 on 2022-07-22 07:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_auto_20220722_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='welldanger',
            old_name='imgRec',
            new_name='imgrec',
        ),
        migrations.RenameField(
            model_name='welldanger',
            old_name='imgResult',
            new_name='imgresult',
        ),
        migrations.AlterField(
            model_name='admin',
            name='create_time',
            field=models.DateField(default=datetime.datetime(2022, 7, 22, 7, 56, 7, 612989, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
